/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DotwellKnownOauthProtectedResourceResRouteImport } from './routes/[.]well-known/oauth-protected-resource/res'
import { Route as ApiAuthDotwellKnownOpenidConfigurationRouteImport } from './routes/api/auth/[.]well-known/openid-configuration'
import { Route as ApiAuthDotwellKnownOauthAuthorizationServerRouteImport } from './routes/api/auth/[.]well-known/oauth-authorization-server'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceResRoute =
  DotwellKnownOauthProtectedResourceResRouteImport.update({
    id: '/.well-known/oauth-protected-resource/res',
    path: '/.well-known/oauth-protected-resource/res',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDotwellKnownOpenidConfigurationRoute =
  ApiAuthDotwellKnownOpenidConfigurationRouteImport.update({
    id: '/api/auth/.well-known/openid-configuration',
    path: '/api/auth/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDotwellKnownOauthAuthorizationServerRoute =
  ApiAuthDotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/api/auth/.well-known/oauth-authorization-server',
    path: '/api/auth/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-protected-resource/res': typeof DotwellKnownOauthProtectedResourceResRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/.well-known/oauth-authorization-server': typeof ApiAuthDotwellKnownOauthAuthorizationServerRoute
  '/api/auth/.well-known/openid-configuration': typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-protected-resource/res': typeof DotwellKnownOauthProtectedResourceResRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/.well-known/oauth-authorization-server': typeof ApiAuthDotwellKnownOauthAuthorizationServerRoute
  '/api/auth/.well-known/openid-configuration': typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-protected-resource/res': typeof DotwellKnownOauthProtectedResourceResRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/.well-known/oauth-authorization-server': typeof ApiAuthDotwellKnownOauthAuthorizationServerRoute
  '/api/auth/.well-known/openid-configuration': typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oauth/consent'
    | '/.well-known/oauth-protected-resource/res'
    | '/api/auth/$'
    | '/api/auth/.well-known/oauth-authorization-server'
    | '/api/auth/.well-known/openid-configuration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth/consent'
    | '/.well-known/oauth-protected-resource/res'
    | '/api/auth/$'
    | '/api/auth/.well-known/oauth-authorization-server'
    | '/api/auth/.well-known/openid-configuration'
  id:
    | '__root__'
    | '/'
    | '/oauth/consent'
    | '/.well-known/oauth-protected-resource/res'
    | '/api/auth/$'
    | '/api/auth/.well-known/oauth-authorization-server'
    | '/api/auth/.well-known/openid-configuration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthConsentRoute: typeof OauthConsentRoute
  DotwellKnownOauthProtectedResourceResRoute: typeof DotwellKnownOauthProtectedResourceResRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthDotwellKnownOauthAuthorizationServerRoute: typeof ApiAuthDotwellKnownOauthAuthorizationServerRoute
  ApiAuthDotwellKnownOpenidConfigurationRoute: typeof ApiAuthDotwellKnownOpenidConfigurationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/res': {
      id: '/.well-known/oauth-protected-resource/res'
      path: '/.well-known/oauth-protected-resource/res'
      fullPath: '/.well-known/oauth-protected-resource/res'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceResRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/.well-known/openid-configuration': {
      id: '/api/auth/.well-known/openid-configuration'
      path: '/api/auth/.well-known/openid-configuration'
      fullPath: '/api/auth/.well-known/openid-configuration'
      preLoaderRoute: typeof ApiAuthDotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/.well-known/oauth-authorization-server': {
      id: '/api/auth/.well-known/oauth-authorization-server'
      path: '/api/auth/.well-known/oauth-authorization-server'
      fullPath: '/api/auth/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof ApiAuthDotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthConsentRoute: OauthConsentRoute,
  DotwellKnownOauthProtectedResourceResRoute:
    DotwellKnownOauthProtectedResourceResRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthDotwellKnownOauthAuthorizationServerRoute:
    ApiAuthDotwellKnownOauthAuthorizationServerRoute,
  ApiAuthDotwellKnownOpenidConfigurationRoute:
    ApiAuthDotwellKnownOpenidConfigurationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
